# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }}, Julia ${{ matrix.config.julia }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release', julia: '1.6'}
          - {os: ubuntu-latest,   r: 'devel', julia: '1.6', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release', julia: '1.6'}
          - {os: ubuntu-latest,   r: 'oldrel-1', julia: '1.6'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
          
      - name: Cache R packages and Julia packages#from JuliaConnectoR
        uses: actions/cache@v3
        with:
          path: | # siehe https://github.com/r-lib/actions/blob/v2/setup-r-dependencies/action.yaml
            ${{ env.R_LIBS_USER }}/*
            !${{ env.R_LIBS_USER }}/pak
            ~/.julia/artifacts/
            ~/.julia/packages/
          key: ${{ matrix.config.r }}-${{ matrix.config.julia }}-${{ hashFiles('DESCRIPTION') }}
          
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.config.julia }}
          
      - name: Add dsBaseClient repository
        run: |
          installJuliaPackages()
        shell: Rscript {0}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
