# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }}, Julia ${{ matrix.config.julia }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release', julia: '1.9'}
          - {os: macos-latest,   r: 'devel', julia: '1.9', http-user-agent: 'release'}
          - {os: macos-latest,   r: 'oldrel-1', julia: '1.9'}
          - {os: ubuntu-latest,   r: 'devel', julia: '1.9', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release', julia: '1.9'}
          - {os: ubuntu-latest,   r: 'oldrel-1', julia: '1.9'}
          - {os: windows-latest,   r: 'devel', julia: '1.9', http-user-agent: 'release'}
          - {os: windows-latest,   r: 'release', julia: '1.9'}
          - {os: windows-latest,   r: 'oldrel-1', julia: '1.9'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      R_LIBS_USER: C:\Temp\Library
      RSPM: https://packagemanager.posit.co/cran/latest
      RENV_CONFIG_REPOS_OVERRIDE: https://packagemanager.posit.co/cran/latest
      TZ: UTC
      _R_CHECK_SYSTEM_CLOCK_: FALSE
      NOT_CRAN: true

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
          
      - name: Cache R packages and Julia packages
        uses: actions/cache@v3
        with:
          path: | 
            ${{ env.R_LIBS_USER }}/*
            !${{ env.R_LIBS_USER }}/pak
            ~/.julia/artifacts/
            ~/.julia/packages/
          key: ${{ matrix.config.r }}-${{ matrix.config.julia }}-${{ hashFiles('DESCRIPTION') }}
          
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.config.julia }}
          
      - name: Add dsBaseClient repository
        run: |
          install.packages("JuliaConnectoR")
          strings1 <- c('"Random"', '"Distributions"', 
                        '"ForwardDiff"', '"Optim"', '"StatsBase"',
                        '"LineSearches"', '"LinearAlgebra"')
          strings2 <- c("Random", "Distributions", 
                        "ForwardDiff", "Optim", "StatsBase",
                        "LineSearches", "LinearAlgebra")
          for (i in 1:length(strings1)){
            if (!JuliaConnectoR::juliaEval(paste0(strings1[i], ' in keys(Pkg.project().dependencies)'))){
              JuliaConnectoR::juliaEval("using Pkg")
              JuliaConnectoR::juliaEval(paste0('Pkg.add("', strings2[i], '")') )
            }
          }
        shell: Rscript {0}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true

