on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.os }}

    name: "${{ matrix.os }} (R-${{ matrix.r }}, Julia-${{ matrix.julia }})"

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        r: ['release', 'devel', 'oldrel-1']
        julia: ['1.9']
        include:
          - os: windows-latest
            r: 'devel'
            julia: '1.9'
            http-user-agent: 'release'
          - os: ubuntu-latest
            r: 'devel'
            julia: '1.9'
            http-user-agent: 'release'
          - os: macos-latest
            r: 'devel'
            julia: '1.9'
            http-user-agent: 'release'

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      RSPM: https://packagemanager.posit.co/cran/latest
      RENV_CONFIG_REPOS_OVERRIDE: https://packagemanager.posit.co/cran/latest
      TZ: UTC
      _R_CHECK_SYSTEM_CLOCK_: FALSE
      NOT_CRAN: true

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r }}
          http-user-agent: ${{ matrix.http-user-agent }}
          use-public-rspm: true

      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia }}
        env:
          JULIA_PKG_USE_CLI_GIT: true
        shell: pwsh

      - name: Cache R & Julia packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.local/share/R/*
            ~/R/*
            ~/.julia/packages
            ~/.julia/artifacts
          key: ${{ runner.os }}-R${{ matrix.r }}-Julia${{ matrix.julia }}-${{ hashFiles('DESCRIPTION') }}

      - name: Install Julia dependencies
        run: |
          julia -e '
            using Pkg
            Pkg.add(["Random", "Distributions", "ForwardDiff", "Optim", "StatsBase",
                     "LineSearches", "LinearAlgebra", "FreqTables", "DataFrames"])
          '

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true

