# Derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? https://github.com/r-lib/actions#where-to-find-help

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RSPM: https://packagemanager.posit.co/cran/latest
      NOT_CRAN: true

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr

      - name: Run test coverage
        run: |
          covr::codecov()
        shell: Rscript {0}

      - name: Show testthat logs
        if: always()
        run: |
          find . -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload test failure artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-test-failures
          path: check/*.Rcheck/tests/testthat.Rout.fail
